Paths:
 Original Projects Path: /studio/projects/
 Target Projects Path: 'someuser@192.666.9.333:/nas/projects/'

Jobs:

 Schema - Templates:
  path: /tank/config/core/
  exclutions:
  - 'hooks'
  - 'install_location.yml'
  - 'pipeline_configuration.yml'
  - 'roots.yml'

 AppHooks:
  path: /tank/config/hooks/
  exclutions:
  - 'README'

 CoreHooks:
  path: /tank/config/core/hooks/
  exclutions:
  - 'README'

 Env Includes:
  path: /tank/config/env/includes/
  exclutions:
  - 'README'

 Environments:
  path: /tank/config/env/
  exclutions:
  - 'includes'

 Icons:
  path: /tank/config/icons/
  exclutions:

